version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
      - ./csv-file.csv:/csv-file.csv
      - ./flows.json:/data/flows.json

volumes:
  node-red-data:

networks:
  node-red-net:
